---
- name: fact devtest_user_home
  shell: "su - {{ devtest_user }} -c 'echo -n $HOME'"
  register: devtest_user_home
  changed_when: false

- name: fact tripleo_root
  shell: "echo -n '{{ devtest_user_home.stdout }}/tripleo'"
  register: tripleo_root
  changed_when: false

- name: fact seed_ip
  shell: "{{ tripleo_root.stdout }}/tripleo-incubator/scripts/os-apply-config -m {{ tripleo_root.stdout }}/testenv.json --key seed-ip --type raw"
  register: seed_ip
  changed_when: false

- name: fact undercloud_ip
  shell: "{{ tripleo_root.stdout }}/tripleo-incubator/scripts/os-apply-config -m {{ tripleo_root.stdout }}/testenv.json --key undercloud.endpointhost --type raw"
  register: undercloud_ip
  changed_when: false

- name: fact ui_tunnel_running
  shell: "ps aux | grep '8111:{{ undercloud_ip.stdout }}:8111' | grep -v grep"
  register: ui_tunnel_running
  changed_when: false
  failed_when: false
