---
- name: clone tuskarclient
  git: repo=git://git.openstack.org/openstack/python-tuskarclient
       dest=/home/heat-admin/python-tuskarclient
       update=no

- name: set up "venv" tox environment
  shell:
    chdir=/home/heat-admin/python-tuskarclient
    tox -evenv python setup.py develop

- name: set owner of tuskarclient
  file: path=/home/heat-admin/python-tuskarclient
        state=directory
        owner=heat-admin
        group=heat-admin
        recurse=yes

- name: tuskar-shell script
  template: src=tuskar-shell.sh.j2
            dest=/home/heat-admin/tuskar-shell.sh
            owner=heat-admin
            group=heat-admin
            mode=0755
