---
- name: clone tripleo heat templates
  git: repo=git://git.openstack.org/openstack/tripleo-heat-templates
       dest=/home/heat-admin/tripleo-heat-templates
       update=no

- name: clone tuskar api
  git: repo=git://git.openstack.org/openstack/tuskar
       dest=/home/heat-admin/tuskar
       update=no

- name: tuskar config
  template: src=tuskar.conf.j2
            dest=/home/heat-admin/tuskar/etc/tuskar/tuskar.conf

# prepare env so that we can run tuskar-dbsync and tuskar-api
- name: run tuskar tox -epy27
  shell:
    chdir=/home/heat-admin/tuskar
    tox -epy27

- name: tuskar-dbsync script
  template: src=tuskar-dbsync.sh.j2
            dest=/home/heat-admin/tuskar-dbsync.sh
            owner=heat-admin
            group=heat-admin
            mode=0755

- name: tuskar-api script
  template: src=tuskar-api.sh.j2
            dest=/home/heat-admin/tuskar-api.sh
            owner=heat-admin
            group=heat-admin
            mode=0755

- name: run tuskar-dbsync
  shell: /home/heat-admin/tuskar-dbsync.sh

- name: set owner of tuskar
  file: path=/home/heat-admin/tuskar
        state=directory
        owner=heat-admin
        group=heat-admin
        recurse=yes

- name: set owner of tripleo-heat-templates
  file: path=/home/heat-admin/tripleo-heat-templates
        state=directory
        owner=heat-admin
        group=heat-admin
        recurse=yes
