---
- name: clone horizon
  git: repo=git://git.openstack.org/openstack/horizon
       dest=/home/heat-admin/horizon
       update=no

- name: clone tuskar-ui
  git: repo=git://git.openstack.org/openstack/tuskar-ui
       dest=/home/heat-admin/tuskar-ui
       update=no

- name: install horizon venv
  shell:
    chdir=/home/heat-admin/horizon
    python tools/install_venv.py

# there's a rumor this also installs something
- name: run horizon tests
  shell:
    chdir=/home/heat-admin/horizon
    ./run_tests.sh -q
  failed_when: false  # ignore any test failures, keep installing

- name: local_settings.py from tuskar-ui to horizon
  shell: cp /home/heat-admin/tuskar-ui/local_settings.py.example /home/heat-admin/horizon/openstack_dashboard/local/local_settings.py

- name: install tuskar-ui deps pt. 1
  shell:
    chdir=/home/heat-admin/horizon
    tools/with_venv.sh pip install -r ../tuskar-ui/requirements.txt

- name: install tuskar-ui deps pt. 2
  shell:
    chdir=/home/heat-admin/horizon
    tools/with_venv.sh pip install -e ../tuskar-ui/

- name: _50_tuskar.py from tuskar-ui to horizon
  shell: cp /home/heat-admin/tuskar-ui/_50_tuskar.py.example /home/heat-admin/horizon/openstack_dashboard/local/enabled/_50_tuskar.py

- name: set owner of horizon
  file: path=/home/heat-admin/horizon
        state=directory
        owner=heat-admin
        group=heat-admin
        recurse=yes

- name: set owner of tuskar-ui
  file: path=/home/heat-admin/tuskar-ui
        state=directory
        owner=heat-admin
        group=heat-admin
        recurse=yes

- name: fact undercloud_tuskar_ui_port_open
  shell: "iptables -L -v | grep tuskar_ui"
  register: undercloud_tuskar_ui_port_open
  changed_when: false
  failed_when: false

- name: open tuskar-ui port on undercloud
  shell: "iptables -I INPUT 3 -p tcp --dport 8111 -j ACCEPT -m comment --comment tuskar_ui"
  when: undercloud_tuskar_ui_port_open.rc != 0

- name: tuskar-ui script
  template: src=tuskar-ui.sh.j2
            dest=/home/heat-admin/tuskar-ui.sh
            owner=heat-admin
            group=heat-admin
            mode=0755
