---
- hosts: tripleo
  roles:
    - { role: tripleo/tuskar_host }

- hosts: tripleo_seed
  roles:
    - { role: tripleo/tuskar_seed }

- hosts: tripleo_undercloud
  sudo: yes
  roles:
    - { role: tripleo/tuskar_undercloud }
