---
- include: user.yml

- name: clone tripleo-incubator
  git: dest={{ devtest_user_home.stdout }}/tripleo/tripleo-incubator
       repo=git://git.openstack.org/openstack/tripleo-incubator
       update=no

- name: tripleo directory owned by devtest user
  file: path={{ devtest_user_home.stdout }}/tripleo
        owner={{ devtest_user }}
        group={{ devtest_user }}
        recurse=yes


- name: fact devtestrc_exists
  shell: test -e {{ devtest_user_home.stdout }}/.devtestrc
  register: devtestrc_exists
  changed_when: false
  failed_when: false

- name: create devtestrc if not present
  template: src=devtestrc.j2
            dest={{ devtest_user_home.stdout }}/.devtestrc
            owner={{ devtest_user }}
            group={{ devtest_user }}
  when: devtestrc_exists.rc != 0
