---
- name: ensure libvirtd group exists
  group: name=libvirtd state=present

- user: name={{ devtest_user }} groups=libvirtd,wheel append=yes

- template: src=sudoers-devtest.j2
            dest=/etc/sudoers.d/devtest
            mode=0440
            validate='visudo -cf %s'
  when: devtest_user != 'root'

- name: fact devtest_user_home
  shell: "su - {{ devtest_user }} -c 'echo -n $HOME'"
  register: devtest_user_home
  changed_when: false

- name: fact devtest_authorized_keys_present
  shell: "[ -e {{ devtest_user_home.stdout }}/.ssh/authorized_keys ]"
  register: devtest_authorized_keys_present
  changed_when: false
  failed_when: false

- file: path={{ devtest_user_home.stdout }}/.ssh
        state=directory
        owner={{ devtest_user }}
        group={{ devtest_user }}
        mode=0700

- name: sync devtest authorized keys with root
  shell: cp /root/.ssh/authorized_keys /home/devtest/.ssh/authorized_keys
  when: devtest_authorized_keys_present.rc != 0 and devtest_user != 'root'

- file: path={{ devtest_user_home.stdout }}/.ssh/authorized_keys
        state=file
        owner={{ devtest_user }}
        group={{ devtest_user }}
        mode=0600
